apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-load-gen
  namespace: boutique
  labels:
    app: boutique
    service: boutique-load-gen
spec:
  selector:
    matchLabels:
      app: boutique
      service: boutique-load-gen
  replicas: 1
  template:
    metadata:
      labels:
        app: boutique
        service: boutique-load-gen
    spec:
      containers:
        - image: aveshatest/boutique-load-gen:latest
          imagePullPolicy: "Always"
          name: boutique-load-gen
          env:
            - name: HOSTNAME
              value: http://frontend:80
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"